ft(login-users): Log in users.
bdirs/bdirs-authentication pull request #19
Opened 2019-08-30 08:34 UTC by FahdJamy

#### Description

Add API endpoint for users to be able to log into the system with either their username or email address.

#### Type of change

Please select the relevant option

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Others (cosmetics, styling, improvements)
- [ ] This change requires a documentation update

#### How Has This Been Tested?

- [x] Unit
- [ ] Integration
- [ ] End-to-end

#### How to Test

- git fetch this branch. `ft-login-users-with-email-or-username-167751966`
- install all packages. run `npm install` or `yarn`
- start the server. `npm run start:dev`

#### Any background context you want to add

in the previous version of the system, user's couldn't log into the system.

#### Story-ID

[Starts #167751966](https://www.pivotaltracker.com/story/show/167751966)

2019-08-31 13:57 UTC, MuhweziDeo requested changes

2019-08-31 13:57 UTC, MuhweziDeo commented on src/services/UserService.ts
> +  public generateToken (payload: object): any {
this should not be in the service layer

2019-08-31 13:57 UTC, MuhweziDeo commented on src/services/UserService.ts
> +  async findUserByEmail(email: string) {
THis is not necessary since the findOne method can take in options have this a bit redundant 
i.e `this.service.findOne({where: {email})`

2019-08-31 13:57 UTC, MuhweziDeo commented on src/services/UserService.ts
> +      console.log(error);
Simply return the error but I dont think we need a try catch on this

2019-09-04 07:39 UTC, FahdJamy commented on src/services/UserService.ts
> +  public generateToken (payload: object): any {
Where should it be sir?

2019-09-05 07:00 UTC, MuhweziDeo commented on src/services/UserService.ts
> +  public generateToken (payload: object): any {
create a helper function in `helpers`

2019-09-06 12:45 UTC, MuhweziDeo requested changes

2019-09-06 12:45 UTC, MuhweziDeo commented on src/api/users/index.ts
> +import { b } from './User.controller';
what is `b`

2019-09-14 08:44 UTC, MuhweziDeo approved these changes
Everything missing shall be included on my PR

2019-09-14 08:46 UTC, merged